version: 1

formatters:
  simple:
    format: "%(message)s"

  datetime:
    format: '%(asctime)s-%(name)s-%(levelname)s: %(message)s'
    datefmt: '%m/%d,%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple

  esay_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: "simple"
    filename: "InfLog.log"

  file_console:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: "datetime"
    filename: "info.log" 
    maxBytes: 10485760 
    backupCount: 20
    encoding: "utf8"

loggers:
  printLogger:
    handlers: [console]
    level: DEBUG
  easylogger:
    handlers: [console,esay_file]
    level: DEBUG

  trainLogger:
    handlers: [console,file_console]
    level: DEBUG

  